spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password: sa123 # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect